#!/usr/bin/env php

<?php
require __DIR__ . '/vendor/autoload.php';

use App\Sort;
use Symfony\Component\Console\Application;

$app = new Application('Dixmod console', 'v1.0.0');
$app->add(new Sort());
$app->run();